#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mailman3"
name = "Mailman3"
description.en = "Electronic mailing lists manager"
description.fr = "Un gestionnaire de liste de discussion par email"

version = "3.3~ynh1"

maintainers = ["decentral1se"]

[upstream]
license = "AGPL-3.0-or-later"
website = "http://www.list.org/"
demo = "https://lists.mailman3.org/mailman3/lists/"
admindoc = "https://docs.mailman3.org/en/latest/"
userdoc = "http://docs.mailman3.org/en/latest/userguide.html"
code = "https://gitlab.com/mailman/mailman-suite"
cpe = "cpe:2.3:a:gnu:mailman"
fund = "https://my.fsf.org/civicrm/contribute/transact?reset=1&id=22"

[integration]
yunohost = ">=11.2"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = ["postgresql", "lynx", "mailman3-full"]

    # Can' use resource helper because we need 2 dbs with specific names…
    # [resources.database]
    # type = "postgresql"
