#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# BACKUP VARIOUS FILES
#=================================================

ynh_backup "/etc/$app/mailman.cfg"
ynh_backup "/etc/$app/mailman-hyperkitty.cfg"
ynh_backup "/etc/$app/mailman-web.py"

ynh_backup "/usr/share/yunohost/hooks/conf_regen/98-postfix_mailman3"

#=================================================
# BACKUP THE POSTGRESQL DATABASE
#=================================================
ynh_print_info "Backing up the PostgreSQL database..."

ynh_psql_dump_db _app" > db_app.sql
ynh_psql_dump_db _web" > db_web.sql

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
