#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

#REMOVEME? ynh_psql_test_if_first_run

# FIXMEhelpers2.1 ynh_psql_create_db --db_user="$db_user_app" --db_name="$db_name_app" --db_pwd="$db_pwd_app"
ynh_psql_db_shell _app"" < "./db_app.sql""

# FIXMEhelpers2.1 ynh_psql_create_db --db_user="$db_user_web" --db_name="$db_name_web" --db_pwd="$db_pwd_web"
ynh_psql_db_shell _web"" < "./db_web.sql""

#=================================================
# RESTORE VARIOUS FILES
#=================================================
ynh_script_progression "Restoring $app's configuration files..."

ynh_restore "/usr/share/yunohost/hooks/conf_regen/98-postfix_mailman3"
yunohost tools regen-conf postfix
ynh_systemctl --service=postfix --action="restart"

ynh_safe_rm "/etc/$app/mailman.cfg"
ynh_restore "/etc/$app/mailman.cfg"

ynh_safe_rm "/etc/$app/mailman-hyperkitty.cfg"
ynh_restore "/etc/$app/mailman-hyperkitty.cfg"

ynh_safe_rm "/etc/$app/mailman-web.py"
ynh_restore "/etc/$app/mailman-web.py"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

systemctl enable "$app.service" --quiet
systemctl enable "$app-web.service" --quiet

yunohost service add "$app" --description="Mailman3 daemon" --log="/var/log/$app/mailman.log"
yunohost service add "$app-web" --description="Mailman3 web daemon" --log="/var/log/$app/web/mailman-web.log"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action=restart
ynh_systemctl --service="$app-web" --action=restart

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
